@host=http://localhost:3000
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "Email":"jo@dot.com",
    "Username":"test"
}
###
# @name login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"binz@dot.com"
}
###
GET {{host}}/api/auth_user
Authorization: Bearer {{login.response.body.Token}}
###
POST {{host}}/api/users/sub/toggle_follow
Authorization: Bearer {{login.response.body.Token}}
###
POST {{host}}/api/posts/1/comments
Authorization: Bearer {{login.response.body.Token}}
Content-Type: application/json

{
    "content":"binz@dot.com"
}
